<?php 

return [
    'Abstract',
    'Animals/Wildlife',
    'Arts',
    'Backgrounds/Textures',
    'Beauty/Fashion',
    'Buildings/Landmarks',
    'Business/Finance',
    'Celebrities',
    'Education',
    'Food and drink',
    'Healthcare/Medical',
    'Holidays',
    'Industrial',
    'Interiors',
    'Miscellaneous',
    'Nature',
    'Objects',
    'Parks/Outdoor',
    'Facebook Cover',
    'Facebook Mobile Cover',
    'Instagram Story',
    'Twitter Banner',
    'YouTube Channel Art',
    'Business Card',
    'Certificate',
    'Coupon',
    'Flyer',
    'Gift Certificate'
];